VCsite/VCsite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainapp.urls', namespace='mainapp'))
]

VCsite/mainapp/urls.py
from django.urls import path, include
from mainapp import views

app_name='mainapp'

urlpatterns = [

    path('chaemoon/', views.index, name='index'),
    path('video', views.video, name='video'),
    path('comment/', views.detail, name='detail'),
    path('redirect/', views.redirect, name='redirect'),
]

VCsite/mainapp/models.py
from django.db import models
from datetime import datetime
# Create your models here.


class Comment(models.Model):

    comment_text = models.CharField(max_length=100)
    pub_date = models.DateTimeField('date published', default=datetime.now())

    def __str__(self):
        return self.comment_text

VCsite/mainapp/views.py
from django.shortcuts import render, reverse
from django.utils import timezone
from django.http import HttpResponseRedirect
from .models import Comment
# Create your views here.


def index(request):
    return render(request, 'mainapp/index.html')


def video(request):
    return render(request, 'mainapp/video.html')


def detail(request):

    comment_list = Comment.objects.all().order_by('-pub_date')[:5]

    return render(request, "mainapp/detail.html", {'comment_list': comment_list})


def redirect(request):

    data = request.POST.get('comment')
    comment = Comment()

    comment.comment_text = data
    comment.pub_date = timezone.now()
    comment.save()

    return HttpResponseRedirect(reverse('mainapp:detail'))

VCsite/mainapp/templates/mainapp/detail.html
{% load staticfiles %}
<!DOCTYPE>
<html lang="ko">
<head>
<meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <style>
    body{
        background-color: #333333;
    }
</style>


<link href="https://fonts.googleapis.com/css?family=Nanum+Brush+Script&display=swap" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Neucha" rel="stylesheet">

</head>

<div style="float:left; margin-left: 100px; margin-top: 250px;">
    <video width="600" height="450" controls loop>
        <source src="{% static 'mainapp/img/chaemoon.mp4' %}" type="video/mp4">
    </video>
    </div>
</div>

<div style="float: right; margin-right:100px; margin-top: 0px;">
    <div style="margin-left:20px;font-family:Neucha;font-size:25px"><h1 style="font-family: 'Nanum Brush Script', cursive;"><font color="#f5f5dc" ><u>꿈꾸는 채문이에게 응원의 메세지를 남겨주세요!</u></font></h1></div>
<div style="border-style:dashed;border-width:3px;background-color:#D4BAA5;margin-top:30px;display:table;width:1000px;height:20px;margin-left:auto;margin-right:auto;">
    <div style="display:table-cell;vertical-align:middle;">
        <div style="margin-top: 100px;">
            <ul>
                <div style="display:table-cell;vertical-align:middle;">
                {% for comment in comment_list %}
                    <li style="font-family: 'Nanum Brush Script', cursive; font-size: 25px"><h1>{{ comment }}</h1></li>
                {% endfor %}
                </div>
            </ul>

            <form method="post" action="{% url 'mainapp:redirect' %}">
                {% csrf_token %}
            <textarea rows="5" cols="70" name="comment" placeholder="응원의 한마디!"></textarea>
            <input type="submit" value="submit" height="30" width="30">

            </form>

        </div>
        </div>
</div>
</div>
<div style="float: left">
<h1 style="margin-left: 100px;"><a href="{% url 'mainapp:index' %}"><font color="#f5f5dc">home으로가기</font></a></h1>
</div>
</html>

VCsite/mainapp/templates/mainapp/video.html
{% load staticfiles %}
<!DOCTYPE>
<html lang="ko">
<head>
<meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<style>
    body{
        background-color: #333333;
    }
</style>

<link href="https://fonts.googleapis.com/css?family=Nanum+Brush+Script&display=swap" rel="stylesheet">
</head>
<div style="float:left; margin-left: 200px; margin-top: 150px;">
    <video width="1000" height="600" controls loop>
        <source src="{% static 'mainapp/img/mad.mp4' %}" type="video/mp4">

    </video>
    </div>
</div>
<div style="float : right; margin-top:300px; margin-right:200px;">

<h1 style="font-family: 'Nanum Brush Script', cursive; font-size: 50px;" ><a href="{% url 'mainapp:detail' %}"><font color="#f5f5dc">더보고싶다면 여기클릭!</font></a></h1>

</div>
<h1 style="font-family: 'Nanum Brush Script', cursive; font-size: 25px; float: left;"><font color="#f5f5dc"> ↙ 영상 클릭!</font></h1>
</html>